[package]
name = "pico-php-tester"
version = "0.1.0"
authors = ["Steffen <steffen.butzer@outlook.com>"]
license = "MIT"

[[bin]]
name = "pico-php-tester"
path = "main.rs"

[dependencies]
pico-php-parser={path="../../"}
glob="0.2"
wait-timeout = "0.1"
clap="2.10.0"

[profile.release]
debug = true